### ISSUE TITLE
How to use in memory?

### ISSUE THREAD

**Issue by celiovasconcelos** [Trendyol/Jdempotent#14]
The medium article says this supports in memory:

> For now, we have in-memory and redis support as datasource preference also if you want to use a different datasource, you can do it by extending to Jdempotent-core project. ( Jdempotent-spring-boot-redis-starter uses Jdempotent-core.)

The conf bellow is not working:

application.properties
```
jdempotent.enable= true
```

pom.xml
```xml
	   <dependency>
	        <groupId>com.trendyol</groupId>
	        <artifactId>Jdempotent-core</artifactId>
	        <version>1.0.3</version>
	    </dependency>
```

Controller
```java
  @IdempotentResource(cachePrefix = "some")
  @PostMapping("/teste/{id}")
  public String teste(@PathVariable("id") Long id) throws Exception {
    System.out.println("!");
    Thread.sleep(5000);
    return "!";
  }
```

**Comment by memojja** [comment]
Hi,

You need to have aspect as a bean that missing part at medium blog post sorry about that. 
We focussed implementation with redis. So for now you can use the following configuration java class and dependencies we will make it easier in the next version.

 ```
@Configuration
public class Config {
    @Bean
    public IdempotentAspect aspect() {
        return new IdempotentAspect();
    }
}```


```
    <dependency>
        <groupId>com.trendyol</groupId>
        <artifactId>Jdempotent-core</artifactId>
        <version>1.0.2</version>
    </dependency>

  <dependency>
      <groupId>org.aspectj</groupId>
      <artifactId>aspectjweaver</artifactId>
      <version>1.7.4</version>
      <scope>compile</scope>
  </dependency>
  ```
