### ISSUE TITLE
Using OpenApi and Spring Boot always I got the object not the String

### ISSUE THREAD

**Issue by fintecheando** [Trendyol/Jdempotent#22]
Hello

When adding the @IdempotentResource(cachePrefix = "CacheResource") in a class with Spring Boot and OpenApi I always fot the Object and not the body, so then the cache has two different keys and then there is not idempotency. 

FIRST REQUEST
fineract-server_1  | 2021-10-27 02:05:35.709 DEBUG 8 --- [nio-8443-exec-8] c.t.j.core.aspect.IdempotentAspect       : ClientsApiResource.create() starting for IdempotentRequestWrapper [request=IdempotentIgnorableWrapper{nonIgnoredFields={serialPersistentFields=[Ljava.io.ObjectStreamField;@199a5ee0, CASE_INSENSITIVE_ORDER=java.lang.String$CaseInsensitiveComparator@408c8a73, coder=0, serialVersionUID=-6849794470754667710, LATIN1=0, UTF16=1, COMPACT_STRINGS=true, value=[B@4b031ff4, hash=0}}]
fineract-server_1  | 2021-10-27 02:05:35.710 DEBUG 8 --- [nio-8443-exec-8] c.t.j.core.aspect.IdempotentAspect       : ClientsApiResource.create() saved to cache with IdempotencyKey [keyValue=ClientsApiResource.create-d379af615329196d4f526ff2aa557]
fineract-server_1  | 2021-10-27 02:05:36.652 DEBUG 8 --- [nio-8443-exec-8] c.t.j.core.aspect.IdempotentAspect       : ClientsApiResource.create() ended for IdempotentRequestWrapper [request=IdempotentIgnorableWrapper{nonIgnoredFields={serialPersistentFields=[Ljava.io.ObjectStreamField;@199a5ee0, CASE_INSENSITIVE_ORDER=java.lang.String$CaseInsensitiveComparator@408c8a73, coder=0, serialVersionUID=-6849794470754667710, LATIN1=0, UTF16=1, COMPACT_STRINGS=true, value=[B@4b031ff4, hash=0}}]

SECOND REQUEST
fineract-server_1  | 2021-10-27 02:05:36.652 DEBUG 8 --- [nio-8443-exec-8] c.t.j.core.aspect.IdempotentAspect       : ClientsApiResource.create() ended for IdempotentRequestWrapper [request=IdempotentIgnorableWrapper{nonIgnoredFields={serialPersistentFields=[Ljava.io.ObjectStreamField;@199a5ee0, CASE_INSENSITIVE_ORDER=java.lang.String$CaseInsensitiveComparator@408c8a73, coder=0, serialVersionUID=-6849794470754667710, LATIN1=0, UTF16=1, COMPACT_STRINGS=true, value=[B@4b031ff4, hash=0}}]
fineract-server_1  | 2021-10-27 02:05:52.284 DEBUG 8 --- [nio-8443-exec-9] c.t.j.core.aspect.IdempotentAspect       : ClientsApiResource.create() starting for IdempotentRequestWrapper [request=IdempotentIgnorableWrapper{nonIgnoredFields={serialPersistentFields=[Ljava.io.ObjectStreamField;@199a5ee0, CASE_INSENSITIVE_ORDER=java.lang.String$CaseInsensitiveComparator@408c8a73, coder=0, serialVersionUID=-6849794470754667710, LATIN1=0, UTF16=1, COMPACT_STRINGS=true, value=[B@6ed5a12a, hash=0}}]
fineract-server_1  | 2021-10-27 02:05:52.287 DEBUG 8 --- [nio-8443-exec-9] c.t.j.core.aspect.IdempotentAspect       : ClientsApiResource.create() saved to cache with IdempotencyKey [keyValue=ClientsApiResource.create-5319fba2c9d479e238c199b671a14]
fineract-server_1  | 2021-10-27 02:05:52.315  WARN 8 --- [nio-8443-exec-9] o.d.jdbc.internal.mysql.MySQLProtocol    : Could not execute query org.drizzle.jdbc.internal.common.query.DrizzleParameterizedQuery@41c19dfc: Duplicate entry '786YYH72' for key 'external_id'
fineract-server_1  | 2021-10-27 02:05:52.330 DEBUG 8 --- [nio-8443-exec-9] c.t.j.core.aspect.IdempotentAspect       : ClientsApiResource.create() deleted from cache with IdempotencyKey [keyValue=ClientsApiResource.create-5319fba2c9d479e238c199b671a14] . Exception : {}

The Java class (Post method):

    @POST
    @Consumes({ MediaType.APPLICATION_JSON })
    @Produces({ MediaType.APPLICATION_JSON })
    @Operation(summary = "Create a Client", description = "Note:\n\n"
            + "1. You can enter either:firstname/middlename/lastname - for a person (middlename is optional) OR fullname - for a business or organisation (or person known by one name).\n"
            + "\n" + "2.If address is enable(enable-address=true), then additional field called address has to be passed.\n\n"
            + "Mandatory Fields: firstname and lastname OR fullname, officeId, active=true and activationDate OR active=false, if(address enabled) address\n\n"
            + "Optional Fields: groupId, externalId, accountNo, staffId, mobileNo, savingsProductId, genderId, clientTypeId, clientClassificationId")
    @IdempotentResource(cachePrefix = "CacheResource")
    @RequestBody(required = true, content = @Content(schema = @Schema(implementation = ClientsApiResourceSwagger.PostClientsRequest.class)))
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = ClientsApiResourceSwagger.PostClientsResponse.class))) })
    public String create(@Parameter(hidden = true) @IdempotentRequestPayload final String apiRequestBodyAsJson) {
        logger.info(apiRequestBodyAsJson);
        final CommandWrapper commandRequest = new CommandWrapperBuilder() //
                .createClient() //
                .withJson(apiRequestBodyAsJson) //
                .build(); //

        final CommandProcessingResult result = this.commandsSourceWritePlatformService.logCommandSource(commandRequest);

        return this.toApiJsonSerializer.serialize(result);
    }

**Comment by IOhacker** [comment]
Hello, I will close the issue, because I have prepared another approach which is a better alternative for the use case that we are trying to solve, I have sent the PR as reference.
