### ISSUE TITLE
Deprecated annotations cause Gradle to fail when using strict options

### ISSUE THREAD

**Issue by IOhacker** [Trendyol/Jdempotent#31]
Hello!

The Gradle compiling task with the option -Werror enabled is failing, because it detectes as deprecated the IdempotentResource and IdempotentRequestPayload

Build Gradle file: https://github.com/apache/fineract/blob/develop/build.gradle 

Full error log https://paste.apache.org/xcnvp

It works commenting the -Werror option, but it is not the best way to do it, because the Apache Fineract Community is expecting to keep the code free of deprecated classes/methods

options.compilerArgs += [
            "-Xlint:unchecked",
            "-Xlint:cast",
            "-Xlint:auxiliaryclass",
            "-Xlint:deprecation",
            "-Xlint:dep-ann",
            "-Xlint:divzero",
            "-Xlint:empty",
            "-Xlint:exports",
            "-Xlint:fallthrough",
            "-Xlint:finally",
            "-Xlint:module",
            "-Xlint:opens",
            "-Xlint:options",
            "-Xlint:overloads",
            "-Xlint:overrides",
            "-Xlint:path",
            "-Xlint:processing",
            "-Xlint:removal",
            "-Xlint:requires-automatic",
            "-Xlint:requires-transitive-automatic",
            "-Xlint:try",
            "-Xlint:varargs",
            "-Xlint:preview",
            "-Xlint:static"
            //,"-Werror"
        ]

**Comment by memojja** [comment]
Hmm, I will be out a new version soon.

**Comment by memojja** [comment]
i pushed new version but maven central sync a little time consumes. I think you can use it after about 10 hours
