### ISSUE TITLE
Query about using the Jdempotent logo in a presentation for Apache Fineract

### ISSUE THREAD

**Issue by IOhacker** [Trendyol/Jdempotent#33]
Hello,

We are preparing a formal presentation about the work that has been done and I want to add the logo of Jdempotent in the presentation and the acknowledgments.

https://docs.google.com/presentation/d/13lw2JqE9ujHVFwmynjJcVIUA3NfcDkbs729VLgadIXE/edit?usp=sharing

Please let me know if this is ok or if I should change anything

Best regards

**Comment by memojja** [comment]
Hello,

Very good news! There is no problem if you use it consciously that it is an MIT License.
We are always open to development. But there is a few typo in slide like JIdempotent instead of Jdempotent :) 

Best regards

**Comment by IOhacker** [comment]
Thank you!!!

I have fixed the typo, added links to this Jdempotent repository and submitted the PR (draft proposal) for the Community review, I hope it can be part of the following Apache Fineract release.

https://github.com/apache/fineract/pull/1951
